### ISSUE TITLE
Issue with extracting archives

### ISSUE THREAD

**Issue by avi-cenna** [makism/mojo-on-fedora40#1]
Hi,

I had some trouble extracting the downloaded archives at first. On my system, which is a stock Fedora 40 Workstation, the archives had the `.xz` suffix, not `.gz`. Once I changed that command I was able to get the other steps to work.

Also, bash is the default shell for Fedora, so it might be good to note that in the instructions.

Nonetheless, thanks for writing this set of instructions!

**Comment by makism** [comment]
Hey @avi-cenna 

Thanks for noticing and reporting. I've updated the document.
